from datetime import time


CHAT_DESTINO = "Trabajos"
HORARIOS_RESUMEN = [
	time(12, 3),
	time(12, 9),
]
VENTANA_ENVIO_MINUTOS = 5
INTERVALO_REINTENTO_SEGUNDOS = 60
MAX_INTENTOS_ENVIO = 3
INTERVALO_COMPROBACION_SEGUNDOS = 15
