from datetime import time


CHAT_DESTINO = "Trabajos"
FECHA_PRUEBA_VENTAS = None
HORARIOS_RESUMEN = [
	time(12, 0),
	time(17, 0),
]
VENTANA_ENVIO_MINUTOS = 5
INTERVALO_REINTENTO_SEGUNDOS = 60
MAX_INTENTOS_ENVIO = 3
INTERVALO_COMPROBACION_SEGUNDOS = 15
